#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-collections
Version  : 2.0
Release  : 1
URL      : https://repo1.maven.org/maven2/commons-collections/commons-collections/2.0/commons-collections-2.0.jar
Source0  : https://repo1.maven.org/maven2/commons-collections/commons-collections/2.0/commons-collections-2.0.jar
Source1  : https://repo1.maven.org/maven2/commons-collections/commons-collections/2.0/commons-collections-2.0.pom
Source2  : https://repo1.maven.org/maven2/commons-collections/commons-collections/2.1/commons-collections-2.1.pom
Source3  : https://repo1.maven.org/maven2/commons-collections/commons-collections/3.1/commons-collections-3.1.pom
Source4  : https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
Source5  : https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.pom
Source6  : https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
Source7  : https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.pom
Source8  : https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2/commons-collections-3.2.jar
Source9  : https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2/commons-collections-3.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.1
Requires: mvn-commons-collections-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-collections package.
Group: Data

%description data
data components for the mvn-commons-collections package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/2.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/2.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/commons-collections/commons-collections/2.0/commons-collections-2.0.jar
/usr/share/java/.m2/repository/commons-collections/commons-collections/2.0/commons-collections-2.0.pom
/usr/share/java/.m2/repository/commons-collections/commons-collections/2.1/commons-collections-2.1.pom
/usr/share/java/.m2/repository/commons-collections/commons-collections/3.1/commons-collections-3.1.pom
/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.pom
/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.pom
/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar
/usr/share/java/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.pom
